// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Uid     int     `form:"uid"`
	Gid     int     `form:"gid"`
	Count   int     `form:"count"`
	Fee     float64 `form:"fee"`
	Subject string  `form:"subject"`
}

type Response struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data OrderInfo `json:"data"`
}

type OrderInfo struct {
	OrderNo string `json:"order_no"`
}

type NRequest struct {
}

type NResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type PRequest struct {
	OrderNo string `form:"order_no"`
}

type PResponse struct {
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
	PayUrl string `json:"pay_url"`
}

type CDRequest struct {
	Uid     int     `form:"uid"`
	Gid     int     `form:"gid"`
	Count   int     `form:"count"`
	Fee     float64 `form:"fee"`
	Subject string  `form:"subject"`
}

type CDResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
