// Code generated by goctl. DO NOT EDIT.
// Source: integral.proto

package server

import (
	"context"

	"2102Aweek3/integral-srv/internal/logic"
	"2102Aweek3/integral-srv/internal/svc"
	"2102Aweek3/integral-srv/pb/integral"
)

type IntegralServer struct {
	svcCtx *svc.ServiceContext
	integral.UnimplementedIntegralServer
}

func NewIntegralServer(svcCtx *svc.ServiceContext) *IntegralServer {
	return &IntegralServer{
		svcCtx: svcCtx,
	}
}

// 随机获取积分
func (s *IntegralServer) SendIntegral(ctx context.Context, in *integral.IRequest) (*integral.IResponse, error) {
	l := logic.NewSendIntegralLogic(ctx, s.svcCtx)
	return l.SendIntegral(in)
}
