// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"2102Amonth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/create_order",
				Handler: CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/pay_order",
				Handler: PayOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/notify",
				Handler: SyncNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/notify",
				Handler: AsyncNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/create_and_desc_inventory",
				Handler: CreataAndDescHandler(serverCtx),
			},
		},
	)
}
