// Code generated by goctl. DO NOT EDIT.
// Source: inventory_srv.proto

package inventorysrvclient

import (
	"context"

	"inventory_srv/pb/inventory_srv"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AResponse = inventory_srv.AResponse
	AResquest = inventory_srv.AResquest
	DRequest  = inventory_srv.DRequest
	DResponse = inventory_srv.DResponse

	InventorySrv interface {
		// 扣减库存
		DescInventory(ctx context.Context, in *DRequest, opts ...grpc.CallOption) (*DResponse, error)
		// 增加库存
		AddInventory(ctx context.Context, in *AResquest, opts ...grpc.CallOption) (*AResponse, error)
	}

	defaultInventorySrv struct {
		cli zrpc.Client
	}
)

func NewInventorySrv(cli zrpc.Client) InventorySrv {
	return &defaultInventorySrv{
		cli: cli,
	}
}

// 扣减库存
func (m *defaultInventorySrv) DescInventory(ctx context.Context, in *DRequest, opts ...grpc.CallOption) (*DResponse, error) {
	client := inventory_srv.NewInventorySrvClient(m.cli.Conn())
	return client.DescInventory(ctx, in, opts...)
}

// 增加库存
func (m *defaultInventorySrv) AddInventory(ctx context.Context, in *AResquest, opts ...grpc.CallOption) (*AResponse, error) {
	client := inventory_srv.NewInventorySrvClient(m.cli.Conn())
	return client.AddInventory(ctx, in, opts...)
}
