// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: integral.proto

package integral

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Integral int64  `protobuf:"varint,2,opt,name=integral,proto3" json:"integral,omitempty"`
	Type     int64  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *IRequest) Reset() {
	*x = IRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integral_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IRequest) ProtoMessage() {}

func (x *IRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integral_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IRequest.ProtoReflect.Descriptor instead.
func (*IRequest) Descriptor() ([]byte, []int) {
	return file_integral_proto_rawDescGZIP(), []int{0}
}

func (x *IRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IRequest) GetIntegral() int64 {
	if x != nil {
		return x.Integral
	}
	return 0
}

func (x *IRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type IResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *IResponse) Reset() {
	*x = IResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integral_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IResponse) ProtoMessage() {}

func (x *IResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integral_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IResponse.ProtoReflect.Descriptor instead.
func (*IResponse) Descriptor() ([]byte, []int) {
	return file_integral_proto_rawDescGZIP(), []int{1}
}

func (x *IResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_integral_proto protoreflect.FileDescriptor

var file_integral_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x22, 0x53, 0x0a, 0x08, 0x49, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x23, 0x0a, 0x09, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0x43, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c,
	0x12, 0x37, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c,
	0x12, 0x12, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x2e, 0x49, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x2e,
	0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_integral_proto_rawDescOnce sync.Once
	file_integral_proto_rawDescData = file_integral_proto_rawDesc
)

func file_integral_proto_rawDescGZIP() []byte {
	file_integral_proto_rawDescOnce.Do(func() {
		file_integral_proto_rawDescData = protoimpl.X.CompressGZIP(file_integral_proto_rawDescData)
	})
	return file_integral_proto_rawDescData
}

var file_integral_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_integral_proto_goTypes = []interface{}{
	(*IRequest)(nil),  // 0: integral.IRequest
	(*IResponse)(nil), // 1: integral.IResponse
}
var file_integral_proto_depIdxs = []int32{
	0, // 0: integral.Integral.SendIntegral:input_type -> integral.IRequest
	1, // 1: integral.Integral.SendIntegral:output_type -> integral.IResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_integral_proto_init() }
func file_integral_proto_init() {
	if File_integral_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_integral_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_integral_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_integral_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_integral_proto_goTypes,
		DependencyIndexes: file_integral_proto_depIdxs,
		MessageInfos:      file_integral_proto_msgTypes,
	}.Build()
	File_integral_proto = out.File
	file_integral_proto_rawDesc = nil
	file_integral_proto_goTypes = nil
	file_integral_proto_depIdxs = nil
}
