// Code generated by goctl. DO NOT EDIT.
// Source: inventory_srv.proto

package server

import (
	"context"

	"inventory_srv/internal/logic"
	"inventory_srv/internal/svc"
	"inventory_srv/pb/inventory_srv"
)

type InventorySrvServer struct {
	svcCtx *svc.ServiceContext
	inventory_srv.UnimplementedInventorySrvServer
}

func NewInventorySrvServer(svcCtx *svc.ServiceContext) *InventorySrvServer {
	return &InventorySrvServer{
		svcCtx: svcCtx,
	}
}

// 扣减库存
func (s *InventorySrvServer) DescInventory(ctx context.Context, in *inventory_srv.DRequest) (*inventory_srv.DResponse, error) {
	l := logic.NewDescInventoryLogic(ctx, s.svcCtx)
	return l.DescInventory(in)
}

// 增加库存
func (s *InventorySrvServer) AddInventory(ctx context.Context, in *inventory_srv.AResquest) (*inventory_srv.AResponse, error) {
	l := logic.NewAddInventoryLogic(ctx, s.svcCtx)
	return l.AddInventory(in)
}
